---
- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars_files:
  - vars.yml
  tasks:
  - replace:
      dest: inventory/aws/hosts/ec2.ini
      regexp: "^# instance_filters = tag:env=staging"
      replace: "instance_filters = tag:env={{ cluster_id }}"
  - replace:
      dest: inventory/aws/hosts/ec2.ini
      regexp: "^instance_filters = tag:env=(.*)"
      replace: "instance_filters = tag:env={{ cluster_id }}"
